### ISSUE TITLE
Sonatype staging repository - close failed due to missing javadoc

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-argumentation#15]
Closing staged repository for 0.1.0 on Sonatype failed:

Event: Failed: Javadoc Validation
typeId  javadoc-staging
failureMessage  Missing: no javadoc jar found in folder '/org/dkpro/argumentation/dkpro-argumentation-examples/0.1.0'

**Comment by reckart** [comment]
Why is there no JavaDoc?

**Comment by habernal** [comment]
I guess because of Java 1.8. Javadoc generation should have failed much earlier (at best locally before releasing to sonatype) but it didn't. But don't ask me why... Configuring mvn:release to work is p\* i\* a*.

**Comment by reckart** [comment]
If there is no JavaDoc Jar, sounds more like somebody explicitly disabled JavaDoc generation.

**Comment by habernal** [comment]
Well if I run javadoc:javadoc, this only package was failing (now it's fixed). But why didn't it fail during the mvn -DautoVersionSubmodules release:prepare process?

**Comment by reckart** [comment]
My guess: It would have failed. But instead of fixing the problem properly, the failing package was included by somebody, probably @githubcstahlhut in the top-level POM of DKPro Argumentation:

```
<excludePackageNames>tutorial*</excludePackageNames>
```

So no JavaDoc was generated for the examples module. Makes sense, right? Creating an empty JAR would be kinda stupid.

You should now remove that exclude.

Fixing instead of working around avoids problems in the long run ;)

**Comment by habernal** [comment]
Fixed. Sonatype "Close" operation output: `Event: All rules passed: Central Sync Requirement`
